---
language: node_js
node_js:
    - '10'

sudo: false

env:
    - SKIP_DEPENDENCY_CHECKER=true

cache:
    directories:
        - $HOME/.npm

before_install:
    - npm config set spin false

install:
    - npm install --only=dev

script:
    - npm test
